version: "3"
services:
  postgis:
    image: kartoza/postgis:9.6-2.4
    volumes:
      - ${HOME}/Tilemill/postgres_data:/var/lib/postgresql
    ports:
      - 5432
  tilemill:
    image: "apbarratt/tilemill"
    volumes:
      - ${HOME}/Tilemill/Projects:/root/Documents/MapBox
      - ${HOME}/Tilemill/Downloads:/root/Downloads
    ports:
      - 20009
      - 20008
    environment:
      - TILEMILL_HOST=localhost
      - TILEMILL_PORT=80
      - PGHOST=postgis
      - PGPORT=5432
      - PGDATABASE=gis
      - PGUSER=docker
      - PGPASSWORD=docker
    depends_on:
      - postgis
  nginx:
    image: nginx
    restart: always
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /tmp/nginx.conf
    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g \"daemon off;\""
    ports:
      - 80:80
    depends_on:
      - tilemill
